ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER huracan_user IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO huracan_user;
GRANT CREATE SESSION TO huracan_user;
GRANT CREATE TABLE TO huracan_user;
ALTER USER huracan_user QUOTA UNLIMITED ON users;