-- Tabla de Usuarios
CREATE TABLE users (
                       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR2(100) NOT NULL,
                       email VARCHAR2(100) UNIQUE NOT NULL,
                       password VARCHAR2(255) NOT NULL,
                       role VARCHAR2(50) CHECK (role IN ('ADMIN', 'CASHIER')) NOT NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de Productos
CREATE TABLE products (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR2(100) NOT NULL,
                          description VARCHAR2(255),
                          price NUMBER(10,2) NOT NULL,
                          stock NUMBER NOT NULL,
                          category VARCHAR2(50) NOT NULL,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de Clientes
CREATE TABLE customers (
                           id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR2(100) NOT NULL,
                           email VARCHAR2(100) UNIQUE,
                           phone VARCHAR2(20),
                           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de Ventas
CREATE TABLE sales (
                       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       customer_id NUMBER,
                       user_id NUMBER NOT NULL,
                       total NUMBER(10,2) NOT NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       CONSTRAINT fk_sales_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
                       CONSTRAINT fk_sales_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Tabla de Detalles de Venta
CREATE TABLE sale_details (
                              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              sale_id NUMBER NOT NULL,
                              product_id NUMBER NOT NULL,
                              quantity NUMBER NOT NULL,
                              price NUMBER(10,2) NOT NULL,
                              subtotal NUMBER(10,2) NOT NULL,
                              CONSTRAINT fk_sale_details_sale FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE,
                              CONSTRAINT fk_sale_details_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- Tabla de Proveedores
CREATE TABLE suppliers (
                           id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR2(100) NOT NULL,
                           phone VARCHAR2(20),
                           email VARCHAR2(100) UNIQUE,
                           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de Compras a Proveedores
CREATE TABLE purchases (
                           id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           supplier_id NUMBER NOT NULL,
                           user_id NUMBER NOT NULL,
                           total NUMBER(10,2) NOT NULL,
                           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                           CONSTRAINT fk_purchases_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
                           CONSTRAINT fk_purchases_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Tabla de Detalles de Compras
CREATE TABLE purchase_details (
                                  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  purchase_id NUMBER NOT NULL,
                                  product_id NUMBER NOT NULL,
                                  quantity NUMBER NOT NULL,
                                  price NUMBER(10,2) NOT NULL,
                                  subtotal NUMBER(10,2) NOT NULL,
                                  CONSTRAINT fk_purchase_details_purchase FOREIGN KEY (purchase_id) REFERENCES purchases(id) ON DELETE CASCADE,
                                  CONSTRAINT fk_purchase_details_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);