CREATE TABLE audit (
                       audit_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       table_name     VARCHAR2(50),
                       operation      VARCHAR2(10),
                       record_id      NUMBER,
                       changed_by     VARCHAR2(100),
                       change_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       old_data       CLOB,
                       new_data       CLOB
);
/